
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-chat-application:/data/db
    networks: 
      - chat-network
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo
    networks: 
      - chat-network 
    restart: unless-stopped

  message-service:
    build: ./message-service
    container_name: message-service
    env_file:
      - ./message-service/.env
    depends_on:
      - mongo
    networks: 
      - chat-network
    restart: unless-stopped

  chat-service:
    build: ./chat-service
    container_name: chat-service
    env_file:
      - ./chat-service/.env
    depends_on:
      - message-service
    networks: 
      - chat-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend-service:/usr/share/nginx/html:ro
    depends_on:
      - auth-service
      - chat-service
      - message-service
    networks: 
      - chat-network
    restart: unless-stopped

volumes:
  mongo-data-chat-application:

networks:
  chat-network: