apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
  namespace: video-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-service
  template:
    metadata:
      labels:
        app: processing-service
    spec:
      contaienrs:
        - name: processing
          image: diwakar5041/processing-service:1.0
          envFrom:
            - configMapRef:
                name: processing-config

