apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: video-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
        - name: upload
          image: upload-service:1.0
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: upload-config
